// Fixture data for the mock API client. The mock is the basis of every
// component test and of the screenshot walkthrough, because the backend is
// being written at the same time as this application. Refer to
// APP-CONTRACT.md section 13.
//
// A tiny silent WAV, base64-encoded, stands in for every mock audio file. It
// decodes to a real, playable (silent) clip so the <audio> element and the
// blob-URL path both exercise real browser code during a screenshot pass.
export const SILENT_WAV_BASE64 =
  "UklGRiQAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQAAAAA=";

export function silentWavBlob(): Blob {
  const bytes = atob(SILENT_WAV_BASE64);
  const arr = new Uint8Array(bytes.length);
  for (let i = 0; i < bytes.length; i++) arr[i] = bytes.charCodeAt(i);
  return new Blob([arr], { type: "audio/wav" });
}

import type {
  ApiKeyInfo,
  Gate,
  Job,
  JobEvent,
  JobStatus,
  LibraryFile,
  ReviewItem,
  SystemStatus,
  Target,
} from "./types";

export const FIXTURE_JOBS: Job[] = [
  {
    id: "job-example-book",
    slug: "example-book",
    title: "Example Book",
    author: "Pete Dexter",
    year: "1988",
    genre: "Fiction",
    language: "en",
    source_path: "/config/library/example-book.epub",
    source_sha256: "9f2c...a01",
    cover_path: null,
    state: "awaiting_qc_review",
    stage: "qc",
    worker: "local",
    priority: 0,
    progress_done: 812,
    progress_total: 812,
    error: null,
    book_config: { engine: { name: "kokoro_cpu", voice: "bm_george", speed: 1.0 } },
    qc_config: { wer_max: 0.15, coverage_min: 0.9 },
    created_at: "20260814T090000Z",
    updated_at: "20260816T110000Z",
    started_at: "20260814T090500Z",
    finished_at: null,
  },
  {
    id: "job-secret-history",
    slug: "the-secret-history",
    title: "The Secret History",
    author: "Donna Tartt",
    year: "1992",
    genre: "Fiction",
    language: "en",
    source_path: "/config/library/the-secret-history.epub",
    source_sha256: "1a7d...c44",
    cover_path: null,
    state: "awaiting_homograph_review",
    stage: "homographs",
    worker: "local",
    priority: 0,
    progress_done: 0,
    progress_total: 0,
    error: null,
    book_config: { engine: { name: "kokoro_cpu", voice: "bm_george", speed: 1.0 } },
    qc_config: {},
    created_at: "20260815T080000Z",
    updated_at: "20260816T090000Z",
    started_at: "20260815T080500Z",
    finished_at: null,
  },
  {
    id: "job-gypo-nolan",
    slug: "example-book-resample",
    title: "A Confederacy of Dunces",
    author: "John Kennedy Toole",
    year: "1980",
    genre: "Fiction",
    language: "en",
    source_path: "/config/library/confederacy-of-dunces.epub",
    source_sha256: "77bb...f10",
    cover_path: null,
    state: "awaiting_sample_approval",
    stage: "sample",
    worker: "local",
    priority: 0,
    progress_done: 0,
    progress_total: 0,
    error: null,
    book_config: { engine: { name: "kokoro_cpu", voice: "bm_george", speed: 1.0 } },
    qc_config: {},
    created_at: "20260816T070000Z",
    updated_at: "20260816T071500Z",
    started_at: "20260816T070200Z",
    finished_at: null,
  },
  {
    id: "job-small-gods",
    slug: "small-gods",
    title: "Small Gods",
    author: "Terry Pratchett",
    year: "1992",
    genre: "Fantasy",
    language: "en",
    source_path: "/config/library/small-gods.epub",
    source_sha256: "44ef...002",
    cover_path: null,
    state: "running",
    stage: "render",
    worker: "local",
    priority: 0,
    progress_done: 340,
    progress_total: 812,
    error: null,
    book_config: { engine: { name: "kokoro_cpu", voice: "bm_george", speed: 1.0 } },
    qc_config: {},
    created_at: "20260816T020000Z",
    updated_at: "20260816T113000Z",
    started_at: "20260816T020500Z",
    finished_at: null,
  },
  {
    id: "job-fifth-season",
    slug: "the-fifth-season",
    title: "The Fifth Season",
    author: "N. K. Jemisin",
    year: "2015",
    genre: "Fantasy",
    language: "en",
    source_path: "/config/library/the-fifth-season.epub",
    source_sha256: "cc10...9de",
    cover_path: null,
    state: "done",
    stage: "deliver",
    worker: "local",
    priority: 0,
    progress_done: 640,
    progress_total: 640,
    error: null,
    book_config: {},
    qc_config: {},
    created_at: "20260812T090000Z",
    updated_at: "20260813T040000Z",
    started_at: "20260812T090500Z",
    finished_at: "20260813T040000Z",
  },
  {
    id: "job-annihilation",
    slug: "annihilation",
    title: "Annihilation",
    author: "Jeff VanderMeer",
    year: "2014",
    genre: "Science Fiction",
    language: "en",
    source_path: "/config/library/annihilation.epub",
    source_sha256: "220a...bb1",
    cover_path: null,
    state: "failed",
    stage: "extract",
    worker: "local",
    priority: 0,
    progress_done: 0,
    progress_total: 0,
    error: "The EPUB holds Adobe DRM. Narratarr does not circumvent DRM.",
    book_config: {},
    qc_config: {},
    created_at: "20260816T060000Z",
    updated_at: "20260816T060100Z",
    started_at: "20260816T060005Z",
    finished_at: "20260816T060100Z",
  },
  {
    id: "job-left-hand",
    slug: "the-left-hand-of-darkness",
    title: "The Left Hand of Darkness",
    author: "Ursula K. Le Guin",
    year: "1969",
    genre: "Science Fiction",
    language: "en",
    source_path: "/config/library/the-left-hand-of-darkness.epub",
    source_sha256: "aa90...123",
    cover_path: null,
    state: "queued",
    stage: null,
    worker: "local",
    priority: 0,
    progress_done: 0,
    progress_total: 0,
    error: null,
    book_config: {},
    qc_config: {},
    created_at: "20260816T113000Z",
    updated_at: "20260816T113000Z",
    started_at: null,
    finished_at: null,
  },
  {
    id: "job-gideon",
    slug: "gideon-the-ninth",
    title: "Gideon the Ninth",
    author: "Tamsyn Muir",
    year: "2019",
    genre: "Fantasy",
    language: "en",
    source_path: "/config/library/gideon-the-ninth.epub",
    source_sha256: "5566...e21",
    cover_path: null,
    state: "paused",
    stage: "chunk",
    worker: "local",
    priority: 0,
    progress_done: 120,
    progress_total: 700,
    error: null,
    book_config: {},
    qc_config: {},
    created_at: "20260815T150000Z",
    updated_at: "20260816T080000Z",
    started_at: "20260815T150500Z",
    finished_at: null,
  },
];

export const FIXTURE_GATES: Gate[] = [
  {
    id: "gate-sample-1",
    job_id: "job-gypo-nolan",
    kind: "sample",
    state: "open",
    payload: { chapter: "ch01", seconds: 91.2 },
    open_items: 1,
    created_at: "20260816T071500Z",
    resolved_at: null,
    resolved_by: null,
    resolution: null,
    reason: null,
    job: {
      id: "job-gypo-nolan",
      slug: "example-book-resample",
      title: "A Confederacy of Dunces",
      author: "John Kennedy Toole",
      cover_path: null,
    },
  },
  {
    id: "gate-homograph-1",
    job_id: "job-secret-history",
    kind: "homograph",
    state: "open",
    payload: {},
    open_items: 2,
    created_at: "20260816T090000Z",
    resolved_at: null,
    resolved_by: null,
    resolution: null,
    reason: null,
    job: {
      id: "job-secret-history",
      slug: "the-secret-history",
      title: "The Secret History",
      author: "Donna Tartt",
      cover_path: null,
    },
  },
  {
    id: "gate-qc-1",
    job_id: "job-example-book",
    kind: "qc",
    state: "open",
    payload: {},
    open_items: 2,
    created_at: "20260816T110000Z",
    resolved_at: null,
    resolved_by: null,
    resolution: null,
    reason: null,
    job: {
      id: "job-example-book",
      slug: "example-book",
      title: "Example Book",
      author: "Pete Dexter",
      cover_path: null,
    },
  },
];

export const FIXTURE_REVIEW_ITEMS: ReviewItem[] = [
  {
    id: "item-wound-1",
    job_id: "job-secret-history",
    gate_id: "gate-homograph-1",
    kind: "homograph_occurrence",
    chapter: "ch04",
    chunk: "0059",
    word: "wound",
    occurrence: 1,
    source_text: null,
    transcript: null,
    context: "A white muffler wound round and round his neck against the cold.",
    wer: null,
    coverage: null,
    duration_s: null,
    flags: [],
    wav_sha256: null,
    candidates: [
      { reading: "verb", phonemes: "wˈWnd", audio: "cand-1" },
      { reading: "noun", phonemes: "wˈuːnd", audio: "cand-2" },
    ],
    state: "open",
    resolution: null,
    reason: null,
    resolved_at: null,
    created_at: "20260816T090000Z",
  },
  {
    id: "item-lead-1",
    job_id: "job-secret-history",
    gate_id: "gate-homograph-1",
    kind: "homograph_occurrence",
    chapter: "ch09",
    chunk: "0114",
    word: "lead",
    occurrence: 2,
    source_text: null,
    transcript: null,
    context: "The old pipes were still lined with lead, Julian said, tapping the sill.",
    wer: null,
    coverage: null,
    duration_s: null,
    flags: [],
    wav_sha256: null,
    candidates: [
      { reading: "noun (metal)", phonemes: "lˈɛd", audio: "cand-1" },
      { reading: "verb (guide)", phonemes: "lˈiːd", audio: "cand-2" },
    ],
    state: "open",
    resolution: null,
    reason: null,
    resolved_at: null,
    created_at: "20260816T090100Z",
  },
  {
    id: "item-qc-0130",
    job_id: "job-example-book",
    gate_id: "gate-qc-1",
    kind: "qc_chunk",
    chapter: "ch07",
    chunk: "0130",
    word: null,
    occurrence: null,
    source_text: "Whisper garbles the proper noun You Connor as its own guess at the sound.",
    transcript: "Whisper garbles the proper noun Ucona as its own guess at the sound.",
    context: null,
    wer: 0.22,
    coverage: 0.95,
    duration_s: 4.1,
    flags: ["wer_high"],
    wav_sha256: "7c1e9f2b4a6d8801f0332211aa99cc7788bbccdd1122334455667788990011",
    candidates: null,
    state: "open",
    resolution: null,
    reason: null,
    resolved_at: null,
    created_at: "20260816T110000Z",
  },
  {
    id: "item-qc-0044",
    job_id: "job-example-book",
    gate_id: "gate-qc-1",
    kind: "qc_chunk",
    chapter: "ch03",
    chunk: "0044",
    word: null,
    occurrence: null,
    source_text: "Gyko!",
    transcript: "jayu",
    context: null,
    wer: 1.0,
    coverage: 0.0,
    duration_s: 2.42,
    flags: ["duration_outlier", "coverage_low"],
    wav_sha256: "aab1120033ffeeddccbbaa99887766554433221100ffeeddccbbaa99887766",
    candidates: null,
    state: "open",
    resolution: null,
    reason: null,
    resolved_at: null,
    created_at: "20260816T110100Z",
  },
  {
    id: "item-qc-0201-voided",
    job_id: "job-example-book",
    gate_id: "gate-qc-1",
    kind: "qc_chunk",
    chapter: "ch11",
    chunk: "0201",
    word: null,
    occurrence: null,
    source_text: "Harry Kessler put his hat on the bar and looked at it for a long moment.",
    transcript: "Harry Kessler put his hat on the bar and looked at it for a long moment.",
    context: null,
    wer: 0.12,
    coverage: 0.97,
    duration_s: 5.6,
    flags: ["wer_high"],
    wav_sha256: "0099aabbccddeeff112233445566778899aabbccddeeff0011223344556677",
    candidates: null,
    state: "voided",
    resolution: "accepted",
    reason:
      "Whisper mishears 'Kessler' as two words the first time through; the audio says the name correctly.",
    resolved_at: "20260815T220000Z",
    created_at: "20260815T219000Z",
  },
];

export const FIXTURE_TARGETS: Target[] = [
  {
    id: "target-folder",
    name: "Output folder",
    kind: "folder",
    enabled: true,
    config: { root: "/output", layout: "{author}/{title}/{title}.m4b", copy_cover: true },
    created_at: "20260810T000000Z",
    updated_at: "20260810T000000Z",
  },
  {
    id: "target-abs",
    name: "Audiobookshelf — House",
    kind: "audiobookshelf",
    enabled: true,
    config: {
      base_url: "http://audiobookshelf:13378",
      library_id: "lib_9f21",
      token_env: "NARRATARR_ABS_TOKEN",
      folder_target: "target-folder",
    },
    created_at: "20260810T000000Z",
    updated_at: "20260812T120000Z",
  },
];

export const FIXTURE_LIBRARY: LibraryFile[] = [
  { path: "/config/library/example-book.epub", size_bytes: 812_000, ingested: true, job_id: "job-example-book" },
  {
    path: "/config/library/the-secret-history.epub",
    size_bytes: 1_040_000,
    ingested: true,
    job_id: "job-secret-history",
  },
  { path: "/config/library/small-gods.epub", size_bytes: 512_000, ingested: true, job_id: "job-small-gods" },
];

export const FIXTURE_KEYS: ApiKeyInfo[] = [
  { id: "key-1", name: "bootstrap", created_at: "20260810T000000Z", last_used_at: "20260816T113000Z" },
];

// The mock mirrors the real response of GET /api/v1/system/status exactly.
// A mock that invents a friendlier shape is worse than no mock: it makes
// every test pass while the real screen throws. That happened here.
export const FIXTURE_SYSTEM_STATUS: SystemStatus = {
  runner_state: "running",
  queue_depth: 2,
  disk_free_bytes: 26_800_000_000,
  models: {
    kokoro_cpu: { present: true, size_bytes: 330_000_000 },
    "faster-whisper-small.en": { present: true, size_bytes: 480_000_000 },
  },
  secrets: { NARRATARR_ABS_TOKEN: { present: true } },
  engine_preflight: {
    espeak_fallback: true,
    warmup_samples: 64_200,
    warmup_sample_rate: 24_000,
    oov_probe_word: "Zyrkovian Quaddlemorph",
    oov_probe_nonempty: true,
    job_slug: null,
    checked_at: "20260817T011731Z",
  },
};

export const FIXTURE_JOB_STATUS: JobStatus = {
  extract: { fresh: 1, stale: 0, absent: 0 },
  normalize: { fresh: 1, stale: 0, absent: 0 },
  chunk: { fresh: 1, stale: 0, absent: 0 },
  sample: { fresh: 1, stale: 0, absent: 0 },
  homographs: { fresh: 1, stale: 0, absent: 0 },
  render: { fresh: 812, stale: 0, absent: 0 },
  qc: { fresh: 810, stale: 0, absent: 2 },
  assemble: { fresh: 0, stale: 0, absent: 22 },
  bind: { fresh: 0, stale: 0, absent: 1 },
  deliver: { fresh: 0, stale: 0, absent: 2 },
};

let eventSeq = 1;
function mkEvent(job_id: string, level: JobEvent["level"], stage: string | null, message: string): JobEvent {
  return { id: eventSeq++, job_id, level, stage, message, data: null, created_at: "20260816T113000Z" };
}

export const FIXTURE_EVENTS: JobEvent[] = [
  mkEvent("job-small-gods", "info", "extract", "Extracted 22 chapters from the EPUB."),
  mkEvent("job-small-gods", "info", "normalize", "Normalized text. 3 caps runs recased."),
  mkEvent("job-small-gods", "info", "chunk", "Made 812 chunks across 22 chapters."),
  mkEvent("job-small-gods", "info", "sample", "Sample rendered and approved."),
  mkEvent("job-small-gods", "info", "homographs", "Homograph audit: 1 class A decision, resolved."),
  mkEvent("job-small-gods", "info", "render", "Rendering chunk 0340 of 812."),
  mkEvent("job-example-book", "warning", "qc", "Chunk ch07/0130 flagged wer_high. Opened for review."),
  mkEvent("job-example-book", "warning", "qc", "Chunk ch03/0044 flagged duration_outlier, coverage_low."),
  mkEvent("job-example-book", "info", "qc", "QC gate opened. 2 chunks need a person."),
  mkEvent("job-annihilation", "error", "extract", "The EPUB holds Adobe DRM. Narratarr does not circumvent DRM."),
];
